version: '3'

services:
  techradar.web:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"

  techradar.services:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ~/clrdbg:/clrdbg:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
