version: '2'

services:
  techradar.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  techradar.services:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
